version: "3.8" 

services:
    graphql:
        depends_on: 
            - mongo
        image: node:14-alpine
        ports:
            - 4000:4000
        volumes:
            - ./graphql/:/myapp
        working_dir: /myapp
        restart: always
        command: sh -c "npm install && node index.js"

    apache:
        image: php:7.2-apache
        ports:
            - 80:80
        volumes:
            - ./web/:/var/www/html

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodata:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        depends_on:
            - mongo
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        restart: always

        